// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EFGetStarted.MyCompiledModels
{
    public partial class BloggingContextModel
    {
        partial void Initialize()
        {
            var blog = BlogEntityType.Create(this);
            var post = PostEntityType.Create(this);

            PostEntityType.CreateForeignKey1(post, blog);

            BlogEntityType.CreateAnnotations(blog);
            PostEntityType.CreateAnnotations(post);

            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
